SELECT A.SCORE,C.ROWNO AS Rank
FROM SCORES A
INNER JOIN (SELECT @ROWNO:=@ROWNO+1 AS ROWNO,SCORE FROM (SELECT DISTINCT SCORE FROM SCORES) A,(SELECT @ROWNO:=0) B ORDER BY SCORE DESC) C
ON A.SCORE=C.SCORE
ORDER BY A.SCORE DESC
;